### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [nescomtm/zad_125#1]
html:
- [x] pogrupuj dolaczanie css i js w headzie. Powinienes najpierw zaciagac pliki css, a potem pliki js (w tym przypadku jQuery), zeby strona najpierw ladowala sie wizualnie, a potem czekala na zaladowanie jQuery. 
Mozesz nawet przeniesc to zaciaganie jQuery tam, gdzie zaciagasz swoj plik js

js:
- [x] masz tu bezrefleksyjne kopiuj-wklej, czesc kodu w ogole nie nalezy do tego zadania, np gdzie uzywasz tego:
```
var $button = $('#get-joke').click(function() {
	getJoke();
});
```
?

**Comment by nescomtm** [comment]
no cóż z tym wklejaniem - moje zdanie juz znasz - poprawione

**Comment by zdolny** [comment]
Nadal w js masz fragmenty kodu, ktorych nie uzywasz

**Comment by nescomtm** [comment]
poczytałem dokładniej .. :)

**Comment by zdolny** [comment]
Lepiej :) ale nadal jest funkcja `getJoke` i zmienna `url`, ktore tutaj nie naleza

**Comment by nescomtm** [comment]
no faktycznie nawet to działa po usunięciu tych zbędnych lini kodu
